name: connect

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  connect:
    name: connect
    runs-on: ubuntu-latest
    steps:
    - uses: self-actuated/connect-ssh@master
